services:
  - type: web
    name: attendance-system
    env: node
    buildCommand: cd client && npm install && npm run build && cd .. && npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://attendance-vardi:vardi2025@cluster0.mvjnk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    autoDeploy: true 